export { default as Header } from './header/Header'
export { default as Features } from './features/Features'
export { default as Paymant } from './paymant/Paymant'
export { default as Gallery } from './gallery/Gallery'
export { default as NewSeason } from './newSeason/NewSeason'
export { default as Footer } from './footer/Footer'